import Foundation
import SwiftData

enum TagCategory: String, Codable {
    case topic
    case concept
    case technology
    case person
    case custom
}

@Model
final class Tag {
    var id: UUID
    var name: String
    var isAutoGenerated: Bool
    var confidence: Float?
    var category: TagCategory

    var items: [Item]

    init(name: String, category: TagCategory = .custom, isAutoGenerated: Bool = false, confidence: Float? = nil) {
        self.id = UUID()
        self.name = name
        self.isAutoGenerated = isAutoGenerated
        self.confidence = confidence
        self.category = category
        self.items = []
    }
}
