import Foundation
import SwiftUI
import SwiftData

enum TagCategory: String, Codable, CaseIterable {
    case topic
    case concept
    case technology
    case person
    case custom

    var displayName: String {
        switch self {
        case .topic: return "Topics"
        case .concept: return "Concepts"
        case .technology: return "Technology"
        case .person: return "People"
        case .custom: return "Custom"
        }
    }

    var iconName: String {
        switch self {
        case .topic: return "text.book.closed"
        case .concept: return "lightbulb"
        case .technology: return "hammer"
        case .person: return "person"
        case .custom: return "tag"
        }
    }

    var color: Color {
        switch self {
        case .topic: return .blue
        case .concept: return .purple
        case .technology: return .orange
        case .person: return .green
        case .custom: return .gray
        }
    }
}

/// Trend direction for tag usage over time
enum TagTrend: String, Codable {
    case increasing
    case stable
    case decreasing
}

@Model
final class Tag {
    var id: UUID
    var name: String
    var isAutoGenerated: Bool
    var confidence: Float?
    var category: TagCategory

    /// Parent tag for informational hierarchy (e.g., "Swift" is parent of "SwiftUI")
    @Relationship(inverse: \Tag.childTags) var parentTag: Tag?
    /// Child tags in the hierarchy
    var childTags: [Tag]

    var items: [Item]
    @Relationship(inverse: \Board.smartRuleTags) var smartRuleBoards: [Board]

    /// Number of items using this tag at last trend calculation
    var previousItemCount: Int
    /// When the trend was last computed
    var trendCalculatedAt: Date?

    init(name: String, category: TagCategory = .custom, isAutoGenerated: Bool = false, confidence: Float? = nil) {
        self.id = UUID()
        self.name = name
        self.isAutoGenerated = isAutoGenerated
        self.confidence = confidence
        self.category = category
        self.parentTag = nil
        self.childTags = []
        self.items = []
        self.smartRuleBoards = []
        self.previousItemCount = 0
        self.trendCalculatedAt = nil
    }

    /// Computed trend based on current vs previous item count
    var trend: TagTrend {
        let current = items.count
        let previous = previousItemCount
        if current > previous + 1 { return .increasing }
        if current < previous - 1 { return .decreasing }
        return .stable
    }
}
