import Foundation
import SwiftData
#if os(macOS)
import AppKit
#endif

// MARK: - Import Item Decision

enum ImportItemDecision: Sendable {
    case importAsNew
    case mergeWithExisting
    case skip
}

// MARK: - Import Preview Item

struct ImportPreviewItem: Identifiable {
    let id: UUID
    let transferItem: TransferItem
    let matchedExistingItem: Item?
    var decision: ImportItemDecision

    var isNew: Bool { matchedExistingItem == nil }
}

// MARK: - Board Package Service

@MainActor
final class BoardPackageService {

    // MARK: - Export

    static func exportPackage(
        board: Board,
        items: [Item],
        options: BoardExportOptions
    ) throws -> Data {
        let boardItemIDs = Set(items.map(\.id))

        let transferItems = items.map { item in
            TransferItem(
                id: item.id,
                title: item.title,
                type: item.type.rawValue,
                status: item.status.rawValue,
                sourceURL: item.sourceURL,
                content: options.includeContent ? item.content : nil,
                tags: options.includeTags ? item.tags.map { tag in
                    TransferTag(
                        name: tag.name,
                        category: tag.category.rawValue,
                        isAutoGenerated: tag.isAutoGenerated
                    )
                } : [],
                createdAt: item.createdAt,
                updatedAt: item.updatedAt
            )
        }

        var transferReflections: [TransferReflection] = []
        if options.includeReflections {
            for item in items {
                for block in item.reflections.sorted(by: { $0.position < $1.position }) {
                    transferReflections.append(TransferReflection(
                        id: block.id,
                        itemID: item.id,
                        blockType: block.blockTypeRaw,
                        content: block.content,
                        highlight: block.highlight,
                        position: block.position,
                        videoTimestamp: block.videoTimestamp,
                        createdAt: block.createdAt
                    ))
                }
            }
        }

        var transferConnections: [TransferConnection] = []
        if options.includeConnections {
            var seenConnectionIDs = Set<UUID>()
            for item in items {
                let outgoing = item.outgoingConnections.filter {
                    guard let targetID = $0.targetItem?.id else { return false }
                    return boardItemIDs.contains(targetID)
                }
                let incoming = item.incomingConnections.filter {
                    guard let sourceID = $0.sourceItem?.id else { return false }
                    return boardItemIDs.contains(sourceID)
                }
                for conn in outgoing + incoming where !seenConnectionIDs.contains(conn.id) {
                    seenConnectionIDs.insert(conn.id)
                    guard let sourceID = conn.sourceItem?.id,
                          let targetID = conn.targetItem?.id else { continue }
                    transferConnections.append(TransferConnection(
                        id: conn.id,
                        sourceItemID: sourceID,
                        targetItemID: targetID,
                        type: conn.type.rawValue,
                        note: conn.note,
                        isAutoGenerated: conn.isAutoGenerated,
                        createdAt: conn.createdAt
                    ))
                }
            }
        }

        let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0.0"
        let manifest = GrovePackageManifest(
            version: 1,
            boardTitle: board.title,
            boardIcon: board.icon,
            boardColor: board.color,
            boardDescription: board.boardDescription,
            exportDate: .now,
            itemCount: items.count,
            groveVersion: appVersion
        )

        let itemOrder = board.manualOrder().filter { boardItemIDs.contains($0) }

        let package = GrovePackage(
            manifest: manifest,
            items: transferItems,
            reflections: transferReflections,
            connections: transferConnections,
            itemOrder: itemOrder
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let jsonData = try encoder.encode(package)

        return try createZipArchive(boardJSON: jsonData, manifest: manifest, encoder: encoder)
    }

    #if os(macOS)
    static func showExportSavePanel(boardTitle: String) -> URL? {
        let panel = NSSavePanel()
        panel.title = "Export Board Package"
        panel.nameFieldStringValue = sanitizeFilename(boardTitle) + ".grove"
        panel.canCreateDirectories = true
        guard panel.runModal() == .OK else { return nil }
        return panel.url
    }
    #endif

    // MARK: - Import

    static func readPackage(url: URL) throws -> GrovePackage {
        let fileData = try Data(contentsOf: url)
        let jsonData = try extractFromZip(fileData)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(GrovePackage.self, from: jsonData)
    }

    static func buildImportPreview(
        package: GrovePackage,
        existingItems: [Item]
    ) -> [ImportPreviewItem] {
        package.items.map { transferItem in
            let matched = existingItems.first { existing in
                guard let existingURL = existing.sourceURL, !existingURL.isEmpty,
                      let transferURL = transferItem.sourceURL, !transferURL.isEmpty else {
                    return false
                }
                return existingURL.lowercased() == transferURL.lowercased()
            }
            return ImportPreviewItem(
                id: transferItem.id,
                transferItem: transferItem,
                matchedExistingItem: matched,
                decision: matched != nil ? .mergeWithExisting : .importAsNew
            )
        }
    }

    static func importPackage(
        package: GrovePackage,
        decisions: [ImportPreviewItem],
        modelContext: ModelContext
    ) throws -> Board {
        let newBoard = Board(
            title: package.manifest.boardTitle,
            icon: package.manifest.boardIcon,
            color: package.manifest.boardColor
        )
        newBoard.boardDescription = package.manifest.boardDescription
        modelContext.insert(newBoard)

        var uuidMap: [UUID: UUID] = [:]
        var itemsByNewID: [UUID: Item] = [:]

        for preview in decisions {
            switch preview.decision {
            case .skip:
                continue

            case .mergeWithExisting:
                guard let existing = preview.matchedExistingItem else { continue }
                uuidMap[preview.transferItem.id] = existing.id
                itemsByNewID[existing.id] = existing
                existing.boards.append(newBoard)

            case .importAsNew:
                let transfer = preview.transferItem
                let itemType = ItemType(rawValue: transfer.type) ?? .article
                let newItem = Item(title: transfer.title, type: itemType)
                newItem.status = ItemStatus(rawValue: transfer.status) ?? .active
                newItem.sourceURL = transfer.sourceURL
                newItem.content = transfer.content
                newItem.createdAt = transfer.createdAt
                newItem.updatedAt = transfer.updatedAt
                modelContext.insert(newItem)

                uuidMap[transfer.id] = newItem.id
                itemsByNewID[newItem.id] = newItem
                newItem.boards.append(newBoard)

                // Tags
                for transferTag in transfer.tags {
                    let existingTag = try? findExistingTag(
                        named: transferTag.name,
                        in: modelContext
                    )
                    if let tag = existingTag {
                        newItem.tags.append(tag)
                    } else {
                        let category = TagCategory(rawValue: transferTag.category) ?? .custom
                        let tag = Tag(
                            name: transferTag.name,
                            category: category,
                            isAutoGenerated: transferTag.isAutoGenerated
                        )
                        modelContext.insert(tag)
                        newItem.tags.append(tag)
                    }
                }
            }
        }

        // Reflections
        for transferReflection in package.reflections {
            guard let newItemID = uuidMap[transferReflection.itemID],
                  let item = itemsByNewID[newItemID] else { continue }
            // Skip reflections for merged items (they already have their own)
            if decisions.first(where: { $0.transferItem.id == transferReflection.itemID })?.decision == .mergeWithExisting {
                continue
            }
            let blockType = ReflectionBlockType(rawValue: transferReflection.blockType) ?? .keyInsight
            let block = ReflectionBlock(
                item: item,
                blockType: blockType,
                content: transferReflection.content,
                highlight: transferReflection.highlight,
                position: transferReflection.position,
                videoTimestamp: transferReflection.videoTimestamp
            )
            block.createdAt = transferReflection.createdAt
            modelContext.insert(block)
        }

        // Connections
        for transferConn in package.connections {
            guard let newSourceID = uuidMap[transferConn.sourceItemID],
                  let newTargetID = uuidMap[transferConn.targetItemID],
                  let sourceItem = itemsByNewID[newSourceID],
                  let targetItem = itemsByNewID[newTargetID] else { continue }
            let connType = ConnectionType(rawValue: transferConn.type) ?? .related
            let conn = Connection(sourceItem: sourceItem, targetItem: targetItem, type: connType)
            conn.note = transferConn.note
            conn.isAutoGenerated = transferConn.isAutoGenerated
            conn.createdAt = transferConn.createdAt
            modelContext.insert(conn)
        }

        // Remap board order
        let newOrder = package.itemOrder.compactMap { uuidMap[$0] }
        newBoard.setManualOrder(newOrder)

        try modelContext.save()
        return newBoard
    }

    // MARK: - Helpers

    private static func findExistingTag(named name: String, in context: ModelContext) throws -> Tag? {
        let lowered = name.lowercased()
        let descriptor = FetchDescriptor<Tag>()
        let allTags = try context.fetch(descriptor)
        return allTags.first { $0.name.lowercased() == lowered }
    }

    private static func sanitizeFilename(_ name: String) -> String {
        let invalidChars = CharacterSet(charactersIn: "/\\:*?\"<>|")
        return name.components(separatedBy: invalidChars).joined(separator: "_")
    }

    // MARK: - Zip Archive (minimal implementation)
    // .grove files are zip archives containing board.json and manifest.json

    private static func createZipArchive(
        boardJSON: Data,
        manifest: GrovePackageManifest,
        encoder: JSONEncoder
    ) throws -> Data {
        let manifestJSON = try encoder.encode(manifest)
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let boardFile = tempDir.appendingPathComponent("board.json")
        let manifestFile = tempDir.appendingPathComponent("manifest.json")
        try boardJSON.write(to: boardFile)
        try manifestJSON.write(to: manifestFile)

        let zipURL = tempDir.appendingPathComponent("archive.zip")
        let coordinator = NSFileCoordinator()
        var error: NSError?

        // Use NSFileCoordinator to create a zip via FileManager
        coordinator.coordinate(
            readingItemAt: tempDir,
            options: .forUploading,
            error: &error
        ) { zipTempURL in
            try? FileManager.default.copyItem(at: zipTempURL, to: zipURL)
        }

        if let error {
            throw error
        }

        return try Data(contentsOf: zipURL)
    }

    private static func extractFromZip(_ data: Data) throws -> Data {
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString)
        let zipFile = tempDir.appendingPathComponent("import.zip")

        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        try data.write(to: zipFile)

        let extractDir = tempDir.appendingPathComponent("extracted")
        try FileManager.default.createDirectory(at: extractDir, withIntermediateDirectories: true)
        try FileManager.default.unzipItem(at: zipFile, to: extractDir)

        let boardFile = extractDir.appendingPathComponent("board.json")
        return try Data(contentsOf: boardFile)
    }
}

// MARK: - FileManager Zip Extension

private extension FileManager {
    func unzipItem(at sourceURL: URL, to destinationURL: URL) throws {
        #if os(macOS)
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/ditto")
        process.arguments = ["-xk", sourceURL.path, destinationURL.path]
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else {
            throw NSError(
                domain: "BoardPackageService",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Failed to unzip package"]
            )
        }
        #else
        // TODO: Implement zip extraction on iOS (e.g. using a third-party library or Apple Archive)
        throw NSError(
            domain: "BoardPackageService",
            code: 2,
            userInfo: [NSLocalizedDescriptionKey: "Zip extraction is not yet supported on iOS"]
        )
        #endif
    }
}
