import SwiftUI
import SwiftData

/// Inspector panel for the iPad detail column.
/// Shows item metadata, board membership, connections, and review toggles.
/// Matches the Mac app's right-column article inspector (InspectorPanelView).
struct ItemInspectorPanel: View {
    @Bindable var item: Item
    @Environment(\.modelContext) private var modelContext
    @Query(sort: \Board.sortOrder) private var allBoards: [Board]

    @State private var showBoardPicker = false
    @State private var isEnrichingItem = false
    @State private var isSuggestingTags = false
    @State private var autoEnrichedItemIDs: Set<UUID> = []

    /// Extract a display domain from the item's sourceURL string.
    private var sourceDomain: String? {
        guard let urlString = item.sourceURL,
              let url = URL(string: urlString),
              let host = url.host(percentEncoded: false) else {
            return nil
        }
        // Strip leading "www." for cleaner display
        if host.hasPrefix("www.") {
            return String(host.dropFirst(4))
        }
        return host
    }

    private var isFetchingMetadata: Bool {
        item.metadata["fetchingMetadata"] == "true"
    }

    private var canRunMetadataEnrichment: Bool {
        item.type == .article && (item.sourceURL?.isEmpty == false)
    }

    private var suggestedTags: [Tag] {
        item.tags.filter { $0.isAutoGenerated }
    }

    private var needsAutomaticEnrichment: Bool {
        guard canRunMetadataEnrichment else { return false }
        let sourceURL = item.sourceURL ?? ""
        let hasResolvedTitle = item.title != sourceURL
        let hasSummary = !(item.metadata["summary"] ?? "").isEmpty
        let hasThumbnail = item.thumbnail != nil || item.metadata["thumbnailURL"] != nil
        let hasAnyTags = !item.tags.isEmpty
        let hasOverview = item.metadata["hasLLMOverview"] == "true"
        let needsTags = LLMServiceConfig.isConfigured && !hasAnyTags
        let needsSummary = LLMServiceConfig.isConfigured && !hasSummary
        let needsOverview = LLMServiceConfig.isConfigured && !hasOverview
        return isFetchingMetadata || !hasResolvedTitle || !hasThumbnail || needsSummary || needsTags || needsOverview
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Spacing.xl) {
                // MARK: - Header
                headerSection

                if let thumbnailData = item.thumbnail {
                    coverImageSection(thumbnailData)
                }

                Divider()

                // MARK: - Metadata
                metadataSection

                Divider()

                // MARK: - AI + Metadata Enrichment
                intelligenceSection

                Divider()

                // MARK: - Boards
                boardsSection

                Divider()

                // MARK: - Connections
                connectionsSection

                Divider()

                // MARK: - Review
                reviewSection

                Spacer()
            }
            .padding(.horizontal, LayoutDimensions.inspectorPaddingH)
            .padding(.top, LayoutDimensions.inspectorPaddingTop)
        }
        .background(Color.bgInspector)
        .sheet(isPresented: $showBoardPicker) {
            boardPickerSheet
        }
        .task(id: item.id) {
            await triggerAutomaticEnrichmentIfNeeded()
        }
    }

    // MARK: - Header

    private var headerSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            HStack(spacing: Spacing.sm) {
                Image(systemName: item.type.iconName)
                    .foregroundStyle(Color.textSecondary)
                Text(item.type.rawValue.capitalized)
                    .font(.groveMeta)
                    .foregroundStyle(Color.textSecondary)
            }

            Text(item.title)
                .font(.groveItemTitle)
                .foregroundStyle(Color.textPrimary)

            if let url = item.sourceURL, !url.isEmpty {
                HStack(spacing: Spacing.xs) {
                    Image(systemName: "link")
                        .font(.system(size: 12))
                    Text(url)
                        .lineLimit(1)
                        .truncationMode(.middle)
                }
                .font(.groveMeta)
                .foregroundStyle(Color.textMuted)
            }
        }
    }

    // MARK: - Metadata

    private func coverImageSection(_ thumbnailData: Data) -> some View {
        CoverImageView(
            imageData: thumbnailData,
            height: 160,
            showPlayOverlay: item.type == .video,
            cornerRadius: 8,
            contentMode: item.type == .article ? .fit : .fill
        )
    }

    private var metadataSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            metadataRow(
                icon: "calendar",
                label: "Created",
                value: item.createdAt.formatted(date: .abbreviated, time: .shortened)
            )
            metadataRow(
                icon: "calendar.badge.clock",
                label: "Updated",
                value: item.updatedAt.formatted(date: .abbreviated, time: .shortened)
            )
            if let domain = sourceDomain {
                metadataRow(icon: "globe", label: "Source", value: domain)
            }
        }
    }

    // MARK: - AI + Metadata

    @ViewBuilder
    private var intelligenceSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            HStack {
                Text("AI + Metadata")
                    .sectionHeaderStyle()
                Spacer()
                if canRunMetadataEnrichment {
                    Button {
                        Task { await runEnrichmentPipeline() }
                    } label: {
                        if isEnrichingItem {
                            ProgressView()
                                .controlSize(.small)
                        } else {
                            Label("Refresh", systemImage: "sparkles")
                                .font(.groveMeta)
                        }
                    }
                    .buttonStyle(.plain)
                    .disabled(isEnrichingItem || isSuggestingTags)
                    .accessibilityLabel("Refresh metadata and AI summary")
                }
            }

            if isFetchingMetadata || isEnrichingItem {
                HStack(spacing: Spacing.sm) {
                    ProgressView()
                        .controlSize(.small)
                    Text("Fetching metadata and generating AI summary…")
                        .font(.groveMeta)
                        .foregroundStyle(Color.textSecondary)
                }
            }

            if let summary = item.metadata["summary"], !summary.isEmpty {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Summary")
                        .font(.groveMeta)
                        .foregroundStyle(Color.textMuted)
                    Text(summary)
                        .font(.groveBodySecondary)
                        .foregroundStyle(Color.textSecondary)
                        .lineLimit(4)
                }
            } else if canRunMetadataEnrichment {
                Text("No summary yet.")
                    .font(.groveBodySecondary)
                    .foregroundStyle(Color.textMuted)
            }

            if item.metadata["hasLLMOverview"] == "true" {
                HStack(spacing: Spacing.xs) {
                    Image(systemName: "sparkles")
                        .font(.system(size: 10))
                    Text("AI overview available in reader")
                        .font(.groveMeta)
                }
                .foregroundStyle(Color.textSecondary)
            }

            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    Text("Tag Suggestions")
                        .font(.groveMeta)
                        .foregroundStyle(Color.textMuted)
                    Spacer()
                    Button {
                        suggestTags()
                    } label: {
                        if isSuggestingTags {
                            ProgressView()
                                .controlSize(.small)
                        } else {
                            Text("Suggest")
                                .font(.groveMeta)
                        }
                    }
                    .buttonStyle(.plain)
                    .disabled(isSuggestingTags || isEnrichingItem)
                    .accessibilityLabel("Suggest tags for this item")
                }

                if !item.tags.isEmpty {
                    FlowLayout(spacing: 4) {
                        ForEach(item.tags.prefix(8)) { tag in
                            if tag.isAutoGenerated {
                                TagChip(tag: tag, mode: .autoTag(
                                    onConfirm: { confirmTag(tag) },
                                    onDismiss: { dismissTag(tag) }
                                ))
                            } else {
                                TagChip(tag: tag, mode: .display)
                            }
                        }
                    }
                } else {
                    Text("No tags yet.")
                        .font(.groveBodySecondary)
                        .foregroundStyle(Color.textMuted)
                }
            }

            if !suggestedTags.isEmpty {
                Text("Confirm suggested tags with checkmark, or remove with x.")
                    .font(.groveMeta)
                    .foregroundStyle(Color.textTertiary)
            }
        }
    }

    private func metadataRow(icon: String, label: String, value: String) -> some View {
        HStack(spacing: Spacing.sm) {
            Image(systemName: icon)
                .font(.system(size: 12))
                .foregroundStyle(Color.textMuted)
                .frame(width: 16)
            Text(label)
                .font(.groveMeta)
                .foregroundStyle(Color.textMuted)
            Spacer()
            Text(value)
                .font(.groveMeta)
                .foregroundStyle(Color.textSecondary)
                .lineLimit(1)
        }
    }

    // MARK: - Boards

    private var boardsSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            HStack {
                Text("Boards")
                    .sectionHeaderStyle()
                Spacer()
                Button {
                    showBoardPicker = true
                } label: {
                    Image(systemName: "plus.circle")
                        .font(.system(size: 14))
                        .foregroundStyle(Color.textMuted)
                }
                .frame(minWidth: LayoutDimensions.minTouchTarget,
                       minHeight: LayoutDimensions.minTouchTarget)
            }

            if item.boards.isEmpty {
                Text("Not in any board")
                    .font(.groveBodySecondary)
                    .foregroundStyle(Color.textMuted)
            } else {
                ForEach(item.boards) { board in
                    HStack(spacing: Spacing.sm) {
                        Image(systemName: board.icon ?? "folder")
                            .font(.system(size: 12))
                            .foregroundStyle(Color.textSecondary)
                        Text(board.title)
                            .font(.groveBody)
                            .foregroundStyle(Color.textPrimary)
                    }
                }
            }
        }
    }

    // MARK: - Connections

    private var connectionsSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            HStack {
                Text("Connections")
                    .sectionHeaderStyle()
                Spacer()
            }

            let outgoing = item.outgoingConnections
            let incoming = item.incomingConnections

            if outgoing.isEmpty && incoming.isEmpty {
                Text("No connections")
                    .font(.groveBodySecondary)
                    .foregroundStyle(Color.textMuted)
            } else {
                ForEach(outgoing) { connection in
                    connectionRow(connection: connection, isOutgoing: true)
                }
                ForEach(incoming) { connection in
                    connectionRow(connection: connection, isOutgoing: false)
                }
            }
        }
    }

    private func connectionRow(connection: Connection, isOutgoing: Bool) -> some View {
        HStack(spacing: Spacing.sm) {
            Image(systemName: isOutgoing ? "arrow.right.circle" : "arrow.left.circle")
                .font(.system(size: 12))
                .foregroundStyle(Color.textSecondary)

            VStack(alignment: .leading, spacing: 2) {
                Text(isOutgoing
                     ? (connection.targetItem?.title ?? "Unknown")
                     : (connection.sourceItem?.title ?? "Unknown"))
                    .font(.groveBodySecondary)
                    .foregroundStyle(Color.textPrimary)
                    .lineLimit(2)

                Text(connection.type.displayLabel)
                    .font(.groveBadge)
                    .foregroundStyle(Color.textTertiary)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(Color.accentBadge)
                    .clipShape(RoundedRectangle(cornerRadius: 3))
            }

            Spacer()
        }
        .padding(.vertical, Spacing.xs)
    }

    // MARK: - Review

    private var reviewSection: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            Text("Review")
                .sectionHeaderStyle()

            if item.isResurfacingEligible {
                Button {
                    item.isResurfacingPaused.toggle()
                    try? modelContext.save()
                } label: {
                    HStack(spacing: Spacing.sm) {
                        Image(systemName: item.isResurfacingPaused ? "circle" : "checkmark.circle.fill")
                            .font(.system(size: 14))
                            .foregroundStyle(item.isResurfacingPaused ? Color.textTertiary : Color.textPrimary)
                        Text("Remind me to revisit")
                            .font(.groveBody)
                            .foregroundStyle(item.isResurfacingPaused ? Color.textSecondary : Color.textPrimary)
                    }
                }
                .buttonStyle(.plain)
                .frame(minHeight: LayoutDimensions.minTouchTarget)

                if let nextDate = item.nextResurfaceDate {
                    HStack(spacing: Spacing.xs) {
                        Image(systemName: item.isResurfacingOverdue ? "exclamationmark.circle" : "calendar.badge.clock")
                            .font(.groveBadge)
                            .foregroundStyle(item.isResurfacingOverdue ? Color.textPrimary : Color.textSecondary)
                        Text(item.isResurfacingOverdue
                             ? "Due for review"
                             : "Next review: \(nextDate.formatted(date: .abbreviated, time: .omitted))")
                            .font(.groveMeta)
                            .fontWeight(item.isResurfacingOverdue ? .semibold : .regular)
                            .foregroundStyle(item.isResurfacingOverdue ? Color.textPrimary : Color.textSecondary)
                    }
                }
            } else {
                Text("Add notes or connections to enable review reminders.")
                    .font(.groveBodySmall)
                    .foregroundStyle(Color.textTertiary)
            }

            if item.type == .article {
                Divider()

                Button {
                    item.isIncludedInDiscussionSuggestions.toggle()
                    item.updatedAt = .now
                    try? modelContext.save()
                } label: {
                    HStack(spacing: Spacing.sm) {
                        Image(systemName: item.isIncludedInDiscussionSuggestions ? "checkmark.circle.fill" : "circle")
                            .font(.system(size: 14))
                            .foregroundStyle(item.isIncludedInDiscussionSuggestions ? Color.textPrimary : Color.textTertiary)
                        Text("Include in discussion suggestions")
                            .font(.groveBody)
                            .foregroundStyle(item.isIncludedInDiscussionSuggestions ? Color.textPrimary : Color.textSecondary)
                    }
                }
                .buttonStyle(.plain)
                .frame(minHeight: LayoutDimensions.minTouchTarget)
            }
        }
    }

    // MARK: - Board Picker

    private var boardPickerSheet: some View {
        NavigationStack {
            List {
                ForEach(allBoards) { board in
                    Button {
                        if !item.boards.contains(where: { $0.id == board.id }) {
                            item.boards.append(board)
                            try? modelContext.save()
                        }
                        showBoardPicker = false
                    } label: {
                        HStack {
                            Label(board.title, systemImage: board.icon ?? "folder")
                                .foregroundStyle(Color.textPrimary)
                            Spacer()
                            if item.boards.contains(where: { $0.id == board.id }) {
                                Image(systemName: "checkmark")
                                    .foregroundStyle(Color.textMuted)
                            }
                        }
                    }
                }
            }
            .navigationTitle("Add to Board")
            #if os(iOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Done") { showBoardPicker = false }
                }
            }
        }
    }

    // MARK: - Enrichment Actions

    private func triggerAutomaticEnrichmentIfNeeded() async {
        guard !autoEnrichedItemIDs.contains(item.id) else { return }
        guard needsAutomaticEnrichment else { return }
        autoEnrichedItemIDs.insert(item.id)
        await runEnrichmentPipeline()
    }

    private func runEnrichmentPipeline() async {
        guard !isEnrichingItem else { return }
        guard let sourceURL = item.sourceURL, !sourceURL.isEmpty else { return }

        isEnrichingItem = true
        item.metadata["fetchingMetadata"] = "true"
        try? modelContext.save()

        let itemID = item.id
        let fallbackTitle = item.title
        let enricher = ItemMetadataEnricher()
        let tagger = ItemAutoTagger()

        let metadata = await enricher.enrichURLItem(
            itemID: itemID,
            urlString: sourceURL,
            context: modelContext
        )

        await tagger.autoTagItem(itemID: itemID, context: modelContext)
        enricher.markSummaryReviewIfNeeded(itemID: itemID, context: modelContext)

        if item.type == .article {
            await enricher.generateOverview(
                itemID: itemID,
                context: modelContext,
                title: metadata.title ?? fallbackTitle,
                description: metadata.description,
                bodyText: metadata.bodyText
            )
            enricher.extractSummaryFallback(itemID: itemID, context: modelContext)
            enricher.markSummaryReviewIfNeeded(itemID: itemID, context: modelContext)
        }

        isEnrichingItem = false
    }

    private func suggestTags() {
        guard !isSuggestingTags else { return }
        isSuggestingTags = true
        let itemID = item.id

        Task {
            let tagger = ItemAutoTagger()
            await tagger.autoTagItem(itemID: itemID, context: modelContext)
            isSuggestingTags = false
        }
    }

    private func confirmTag(_ tag: Tag) {
        tag.isAutoGenerated = false
        item.updatedAt = .now
        try? modelContext.save()
    }

    private func dismissTag(_ tag: Tag) {
        item.tags.removeAll { $0.id == tag.id }
        item.updatedAt = .now
        try? modelContext.save()
    }
}
