import AppKit
import SwiftUI

// MARK: - Growth Stage Indicator

struct GrowthStageIndicator: View {
    let stage: GrowthStage
    var showLabel: Bool = false

    @Environment(\.colorScheme) private var colorScheme

    private var stageColor: Color {
        Color(hex: colorScheme == .dark ? stage.darkColorHex : stage.colorHex)
    }

    var body: some View {
        HStack(spacing: 4) {
            Image(systemName: stage.systemImage)
                .font(.system(size: stage.iconSize))
                .foregroundStyle(stageColor)

            if showLabel {
                Text(stage.displayName)
                    .font(.groveBadge)
                    .foregroundStyle(stageColor)
            }
        }
    }
}

struct ItemCardView: View {
    let item: Item

    var body: some View {
        VStack(alignment: .leading, spacing: Spacing.sm) {
            // Cover image (articles, videos, etc.)
            if let thumbnailData = item.thumbnail {
                CoverImageView(
                    imageData: thumbnailData,
                    height: 120,
                    showPlayOverlay: item.type == .video,
                    cornerRadius: 4
                )
            }

            // Type icon and title
            HStack(alignment: .top, spacing: 8) {
                Image(systemName: item.type.iconName)
                    .font(.system(size: 14))
                    .foregroundStyle(Color.textMuted)
                    .frame(width: 20, height: 20)

                VStack(alignment: .leading, spacing: 3) {
                    Text(item.title)
                        .font(.groveItemTitle)
                        .lineLimit(2)
                        .foregroundStyle(Color.textPrimary)
                        .frame(maxWidth: .infinity, alignment: .leading)

                    if item.metadata["isAIGenerated"] == "true" {
                        HStack(spacing: 3) {
                            Image(systemName: item.metadata["isAIEdited"] == "true" ? "pencil" : "sparkles")
                                .font(.system(size: 8))
                            Text(item.metadata["isAIEdited"] == "true" ? "Edited" : "AI Draft")
                                .font(.groveBadge)
                        }
                        .foregroundStyle(Color.textSecondary)
                    }

                    // Video duration badge
                    if item.type == .video, let durationStr = item.metadata["videoDuration"],
                       let duration = Double(durationStr) {
                        HStack(spacing: 3) {
                            Image(systemName: "clock")
                                .font(.system(size: 8))
                            Text(duration.formattedTimestamp)
                                .font(.groveBadge)
                        }
                        .foregroundStyle(Color.textSecondary)
                    }
                }
            }

            // One-line summary
            if let summary = item.metadata["summary"], !summary.isEmpty {
                Text(summary)
                    .font(.groveBodySecondary)
                    .foregroundStyle(Color.textSecondary)
                    .lineLimit(2)
                    .padding(.leading, 28)
            }

            // Tags row (auto-generated tags have dashed border)
            if !item.tags.isEmpty {
                HStack(spacing: 4) {
                    ForEach(item.tags.prefix(3)) { tag in
                        Text(tag.name)
                            .font(.groveTag)
                            .foregroundStyle(tag.isAutoGenerated ? Color.textSecondary : Color.textPrimary)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 3)
                            .background(Color.bgCard)
                            .clipShape(RoundedRectangle(cornerRadius: 3))
                            .overlay(
                                RoundedRectangle(cornerRadius: 3)
                                    .strokeBorder(
                                        style: tag.isAutoGenerated
                                            ? StrokeStyle(lineWidth: 1, dash: [3, 2])
                                            : StrokeStyle(lineWidth: 1)
                                    )
                                    .foregroundStyle(tag.isAutoGenerated ? Color.borderTagDashed : Color.borderTag)
                            )
                    }
                    if item.tags.count > 3 {
                        Text("+\(item.tags.count - 3)")
                            .font(.groveBadge)
                            .foregroundStyle(Color.textTertiary)
                    }
                }
            }

            Spacer(minLength: 0)

            // Badges row
            HStack(spacing: Spacing.md) {
                GrowthStageIndicator(stage: item.growthStage)
                    .help("\(item.growthStage.displayName) — \(item.depthScore) pts")

                let connectionCount = item.outgoingConnections.count + item.incomingConnections.count
                if connectionCount > 0 {
                    Label("\(connectionCount)", systemImage: "link")
                        .font(.groveMeta)
                        .foregroundStyle(Color.textSecondary)
                }

                if item.reflections.count > 0 {
                    Label("\(item.reflections.count)", systemImage: "text.alignleft")
                        .font(.groveMeta)
                        .foregroundStyle(Color.textSecondary)
                }

                Spacer()

                if item.metadata["videoLocalFile"] == "true" {
                    Text("Local Video")
                        .font(.groveBadge)
                        .foregroundStyle(Color.textTertiary)
                } else if let urlString = item.sourceURL, let url = URL(string: urlString) {
                    Button {
                        NSWorkspace.shared.open(url)
                    } label: {
                        HStack(spacing: 3) {
                            Image(systemName: "arrow.up.right")
                                .font(.system(size: 8))
                            Text(domainFrom(urlString))
                                .font(.groveBadge)
                                .lineLimit(1)
                        }
                        .foregroundStyle(Color.textTertiary)
                    }
                    .buttonStyle(.plain)
                }
            }
        }
        .padding(Spacing.md)
        .frame(maxWidth: .infinity, minHeight: 100, alignment: .topLeading)
        .background(Color.bgCard)
        .clipShape(RoundedRectangle(cornerRadius: 8))
        .overlay(
            RoundedRectangle(cornerRadius: 8)
                .stroke(Color.borderPrimary, lineWidth: 1)
        )
    }

    private func domainFrom(_ urlString: String) -> String {
        guard let url = URL(string: urlString),
              let host = url.host else {
            return urlString
        }
        return host.replacingOccurrences(of: "www.", with: "")
    }
}
