import Foundation
import SwiftData

enum ConnectionType: String, Codable, CaseIterable {
    case related
    case contradicts
    case buildsOn
    case inspiredBy
    case sameTopic

    var displayLabel: String {
        switch self {
        case .related: "Related"
        case .contradicts: "Contradicts"
        case .buildsOn: "Builds On"
        case .inspiredBy: "Inspired By"
        case .sameTopic: "Same Topic"
        }
    }
}

@Model
final class Connection {
    var id: UUID = UUID()
    var sourceItem: Item?
    var targetItem: Item?
    var type: ConnectionType = ConnectionType.related
    var note: String?
    var isAutoGenerated: Bool = false
    var createdAt: Date = Date.now

    init(sourceItem: Item, targetItem: Item, type: ConnectionType) {
        self.id = UUID()
        self.sourceItem = sourceItem
        self.targetItem = targetItem
        self.type = type
        self.note = nil
        self.isAutoGenerated = false
        self.createdAt = .now
    }
}
