import Foundation

// MARK: - Grove Package

struct GrovePackage: Codable, Sendable {
    let manifest: GrovePackageManifest
    let items: [TransferItem]
    let reflections: [TransferReflection]
    let connections: [TransferConnection]
    let itemOrder: [UUID]
}

struct GrovePackageManifest: Codable, Sendable {
    let version: Int
    let boardTitle: String
    let boardIcon: String?
    let boardColor: String?
    let boardDescription: String?
    let exportDate: Date
    let itemCount: Int
    let groveVersion: String
}

// MARK: - Transfer Structs

struct TransferItem: Codable, Sendable, Identifiable {
    let id: UUID
    let title: String
    let type: String
    let status: String
    let sourceURL: String?
    let content: String?
    let tags: [TransferTag]
    let createdAt: Date
    let updatedAt: Date
}

struct TransferTag: Codable, Sendable {
    let name: String
    let category: String
    let isAutoGenerated: Bool
}

struct TransferReflection: Codable, Sendable {
    let id: UUID
    let itemID: UUID
    let blockType: String
    let content: String
    let highlight: String?
    let position: Int
    let videoTimestamp: Int?
    let createdAt: Date
}

struct TransferConnection: Codable, Sendable {
    let id: UUID
    let sourceItemID: UUID
    let targetItemID: UUID
    let type: String
    let note: String?
    let isAutoGenerated: Bool
    let createdAt: Date
}
