import SwiftUI

/// Compact row for inbox items showing title, source domain, thumbnail,
/// auto-tag chips (confirm/dismiss), and time since added.
struct MobileInboxCard: View {
    let item: Item
    var onConfirmTag: ((Tag) -> Void)?
    var onDismissTag: ((Tag) -> Void)?

    private var isFetchingMetadata: Bool {
        item.metadata["fetchingMetadata"] == "true"
    }

    var body: some View {
        HStack(spacing: Spacing.md) {
            // Thumbnail
            if let thumbnailData = item.thumbnail {
                thumbnailImage(thumbnailData)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                    .frame(width: 56, height: 56)
                    .clipShape(RoundedRectangle(cornerRadius: 8))
            }

            VStack(alignment: .leading, spacing: Spacing.xs) {
                // Title
                Text(item.title)
                    .font(.groveItemTitle)
                    .foregroundStyle(Color.textPrimary)
                    .lineLimit(2)

                // Source domain
                if let sourceURL = item.sourceURL,
                   let host = URL(string: sourceURL)?.host(percentEncoded: false) {
                    Text(host)
                        .font(.groveMeta)
                        .foregroundStyle(Color.textTertiary)
                        .lineLimit(1)
                }

                if isFetchingMetadata {
                    HStack(spacing: 4) {
                        ProgressView()
                            .controlSize(.small)
                        Text("Fetching metadata…")
                            .font(.groveMeta)
                            .foregroundStyle(Color.textMuted)
                    }
                } else if let summary = item.metadata["summary"], !summary.isEmpty {
                    Text(summary)
                        .font(.groveBodySecondary)
                        .foregroundStyle(Color.textSecondary)
                        .lineLimit(2)
                } else if let content = item.content, !content.isEmpty {
                    Text(content)
                        .font(.groveBodySecondary)
                        .foregroundStyle(Color.textSecondary)
                        .lineLimit(2)
                }

                // Auto-tag chips
                if !autoTags.isEmpty {
                    HStack(spacing: Spacing.xs) {
                        ForEach(autoTags) { tag in
                            autoTagChip(tag)
                        }
                    }
                }
            }

            Spacer(minLength: 0)

            // Time since added
            Text(compactRelativeTime(from: item.createdAt))
                .font(.groveMeta)
                .foregroundStyle(Color.textMuted)
                .lineLimit(1)
        }
        .padding(.vertical, Spacing.xs)
        #if os(iOS)
        .hoverEffect(.highlight)
        #endif
    }

    // MARK: - Helpers

    private var autoTags: [Tag] {
        item.tags.filter { $0.isAutoGenerated }
    }

    private func autoTagChip(_ tag: Tag) -> some View {
        HStack(spacing: 4) {
            Text(tag.name)
                .font(.groveTag)
                .foregroundStyle(Color.textSecondary)

            if let onConfirmTag {
                Button {
                    onConfirmTag(tag)
                } label: {
                    Image(systemName: "checkmark")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(Color.textSecondary)
                }
                .buttonStyle(.plain)
            }

            if let onDismissTag {
                Button {
                    onDismissTag(tag)
                } label: {
                    Image(systemName: "xmark")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(Color.textMuted)
                }
                .buttonStyle(.plain)
            }
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(Color.bgTagActive.opacity(0.5))
        .clipShape(Capsule())
    }

    private func thumbnailImage(_ data: Data) -> Image {
        #if os(iOS)
        if let uiImage = UIImage(data: data) {
            return Image(uiImage: uiImage)
        }
        #else
        if let nsImage = NSImage(data: data) {
            return Image(nsImage: nsImage)
        }
        #endif
        return Image(systemName: "photo")
    }

    private func compactRelativeTime(from date: Date) -> String {
        let elapsed = max(0, Int(Date.now.timeIntervalSince(date)))

        if elapsed < 3600 {
            let minutes = max(1, elapsed / 60)
            return "\(minutes)m"
        }

        if elapsed < 86_400 {
            let hours = elapsed / 3600
            return "\(hours)h"
        }

        if elapsed < 604_800 {
            let days = elapsed / 86_400
            return "\(days)d"
        }

        if elapsed < 2_592_000 {
            let weeks = elapsed / 604_800
            return "\(weeks)w"
        }

        if elapsed < 31_536_000 {
            let months = elapsed / 2_592_000
            return "\(months)mo"
        }

        let years = elapsed / 31_536_000
        return "\(years)y"
    }
}
